# Backend Dockerfile
FROM node:18.12-alpine3.17 AS backend-builder

# Set the working directory to the server directory
WORKDIR /server

# Copy backend-specific files and install dependencies
COPY ../package.json ../package-lock.json ./
RUN npm install
COPY . .

# Expose and run the backend application
EXPOSE 3000
CMD [ "npm", "start" ]

# The rest of your backend-specific build steps
