# Frontend Dockerfile
FROM node:18.12-alpine3.17 AS frontend-builder

# Set the working directory to the client directory
WORKDIR /usr/src/client

# Copy frontend-specific files and install dependencies
COPY ../package.json ../package-lock.json ./
RUN npm install
COPY . .

# Build the frontend code (e.g., using webpack)
RUN npm run build

# The rest of your frontend build steps




